<a href="https://colab.research.google.com/github/adiggo/Bash/blob/master/torch_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# tensor
tensor = torch.tensor([[[1, 2],
                        [3, 6],
                        [2, 4]]])
tensor

tensor([[[1, 2],
         [3, 6],
         [2, 4]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 2])

In [ ]:
tensor[0]

tensor([[1, 2],
        [3, 6],
        [2, 4]])

Random tensors
random tensors are critical because neural network learn is that they start with random numbers and then adjust random numbers to better represent the data


In [ ]:
# create random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2256, 0.4435, 0.2450, 0.1249],
        [0.3037, 0.1580, 0.7476, 0.4360],
        [0.1620, 0.0262, 0.2198, 0.8583]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
image_tensor = torch.rand(size=(3, 224, 224))
image_tensor.shape, image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
import torch

# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.8239, 0.4296, 0.5762, 0.7555],
        [0.1052, 0.7682, 0.6684, 0.0414],
        [0.4602, 0.3084, 0.0852, 0.2430]])

In [ ]:
random_tensor2 = torch.rand(3, 4, 5)
random_tensor2

tensor([[[0.3772, 0.0283, 0.2280, 0.6272, 0.1977],
         [0.1426, 0.2676, 0.3672, 0.6604, 0.6078],
         [0.1939, 0.1415, 0.4530, 0.6141, 0.2678],
         [0.7698, 0.5070, 0.5477, 0.4690, 0.6113]],

        [[0.8717, 0.3545, 0.1989, 0.8775, 0.1369],
         [0.3124, 0.6068, 0.2981, 0.4837, 0.7606],
         [0.7917, 0.5468, 0.7588, 0.4037, 0.4755],
         [0.3384, 0.8791, 0.7110, 0.5516, 0.6699]],

        [[0.7054, 0.4395, 0.0036, 0.9433, 0.5416],
         [0.0910, 0.4688, 0.2342, 0.9485, 0.1969],
         [0.7746, 0.6788, 0.3395, 0.0162, 0.2104],
         [0.7243, 0.4336, 0.2201, 0.7147, 0.8886]]])

In [ ]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
torch.__version__

'2.3.0+cu121'

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(start=1, end=10, step=2)

tensor([1, 3, 5, 7, 9])

In [ ]:
one_to_ten = torch.arange(start=1, end=10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
import torch
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device="cpu", requires_grad=False) # whether to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
t = torch.rand(3, 4)
t

tensor([[0.1523, 0.9769, 0.8838, 0.7410],
        [0.0902, 0.6672, 0.5949, 0.6586],
        [0.7799, 0.2344, 0.2249, 0.5692]])

In [ ]:
t.size()

torch.Size([3, 4])

In [ ]:
print(f"tensor device: {t.device}")

tensor device: cpu


tensor support:



```
# This is formatted as code
```



In [ ]:
tensor = torch.tensor ([1, 2, 3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor * tensor # element wise multi

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 966 µs


tensor(14)

this is much faster using torch.matmul

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 75 µs, sys: 6 µs, total: 81 µs
Wall time: 85.4 µs


tensor(14)

In [ ]:
tensor.ndim

1

In [ ]:
%%time
tensor * tensor

CPU times: user 1.12 ms, sys: 4 µs, total: 1.12 ms
Wall time: 966 µs


tensor([1, 4, 9])

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2,3))

tensor([[0.1758, 1.0521, 0.8506],
        [0.1126, 0.7200, 0.6302],
        [0.0880, 0.4737, 0.3281]])

the resuling matrix has the shape of outer dimensions


In [ ]:
tensor_a = torch.rand(3,2)
tensor_b = torch.rand(3,2)
torch.mm(tensor_a, tensor_b.T)

# mm is short matmul, however only for matrix

tensor([[0.0624, 0.0692, 0.2812],
        [0.1198, 0.1538, 0.2758],
        [0.2735, 0.3498, 0.6467]])

transpose switch the dimension

In [ ]:
torch.min(tensor)
torch.mean(tensor.type(torch.float32))

tensor(2.)

In [ ]:
tensor.argmax()

tensor(2)

In [ ]:
tensor.argmin()

tensor(0)

In [ ]:
tensor.min()

tensor(1)

reshape --> reshape to defined shape
view --> return a view

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
new_x = torch.rand(1, 9)
new_x


tensor([[0.2275, 0.1378, 0.9043, 0.0929, 0.6097, 0.4980, 0.2020, 0.6969, 0.7667]])

In [ ]:
x = new_x.squeeze()
x

tensor([0.2275, 0.1378, 0.9043, 0.0929, 0.6097, 0.4980, 0.2020, 0.6969, 0.7667])

In [ ]:
new_x1 = x.unsqueeze(dim=1)
new_x1

tensor([[0.2275],
        [0.1378],
        [0.9043],
        [0.0929],
        [0.6097],
        [0.4980],
        [0.2020],
        [0.6969],
        [0.7667]])

In [7]:
# torch.permute
import torch
x = torch.rand(size=(224, 223, 3))
x.size()

x_permuted = torch.permute(x, (2, 0, 1))
# x_permuted and x share the same underlying memory
x = torch.rand(225, 224, 1)
x_permuted.size()

torch.Size([3, 224, 223])

In [19]:
# indexing with pytorch
x = torch.arange(1, 10).reshape(1, 3, 3)
x
x[0]
x[0][0]
x[0][0][0]
x.shape
x.ndim

3

In [29]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [30]:
x[0][0][1]

tensor(2)

In [27]:
x[:, 0]

tensor(2)

In [31]:
x[:, :, 0]

tensor([[1, 4, 7]])

x[:, 0] --> this mean any first dimension, 1st element for second dimension, and any 3rd dimension

In [1]:
import numpy as np
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
array.dtype

dtype('float64')

In [3]:
array+1

array([2., 3., 4., 5., 6., 7., 8.])

In [4]:
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [9]:
## reproducibility
torch.rand(3, 3)

tensor([[0.3349, 0.2233, 0.9886],
        [0.6932, 0.8292, 0.8621],
        [0.1058, 0.6659, 0.1393]])

## reproducibility
to reduce randomness in nn and pytorch comes the concept of a **random seed**. essentially what the random seed does is "flavour" the randomness

In [11]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6436, 0.2073, 0.0720, 0.9458],
        [0.8275, 0.3081, 0.6516, 0.1453],
        [0.6848, 0.4749, 0.6194, 0.3003]])
tensor([[0.5703, 0.7651, 0.1080, 0.3825],
        [0.3857, 0.5647, 0.2044, 0.7165],
        [0.1573, 0.4852, 0.0420, 0.6174]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [14]:
import torch
## different flavor of randomness
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

# random_seed only work on one block of code
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


[link text](https://)